services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - marketplace-network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - marketplace-network

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - marketplace-network
    env_file:
      - order-service/.env.docker

  invoice-service:
    build: ./invoice-service
    container_name: invoice-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - marketplace-network
    env_file:
      - invoice-service/.env.docker

networks:
  marketplace-network:
    driver: bridge
